### ISSUE TITLE
osixia/openldap and not working with ui

### ISSUE THREAD

**Issue by DiponRoy** [wheelybird/ldap-user-manager#174]
I am using this docker-compose file, but if I try to log in using username _**cn=admin,dc=example,dc=org**_ or _**admin**_ and password _**adminpass**_ it says The username and/or password are unrecognised.

```
version: "3.7"

services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    volumes:
      - openldap-data:/var/lib/ldap
      #- ./storage/ldap_config:/etc/ldap/slapd.d
    environment:
      - LDAP_ORGANISATION=example
      - LDAP_DOMAIN=example.org
      - LDAP_ADMIN_PASSWORD=adminpass
      - LDAP_CONFIG_PASSWORD=configpass
      - LDAP_RFC2307BIS_SCHEMA=true
      - LDAP_REMOVE_CONFIG_AFTER_SETUP=true
      - LDAP_TLS_VERIFY_CLIENT=never
    ports:
      - 389:389
      - 636:636
    networks:
      - openldap

  openldap-ui:
    image: wheelybird/ldap-user-manager:v1.7
    container_name: openldap-ui
    environment:
      - LDAP_URI=ldap://openldap:389
      - LDAP_BASE_DN=dc=example,dc=org
      - LDAP_REQUIRE_STARTTLS=TRUE
      - LDAP_ADMINS_GROUP=admins
      - LDAP_ADMIN_BIND_DN=cn=admin,dc=example,dc=org
      - LDAP_ADMIN_BIND_PWD=adminpass
      - LDAP_IGNORE_CERT_ERRORS=true
      - NO_HTTPS=TRUE
      - PASSWORD_HASH=SSHA
      - SERVER_HOSTNAME=localhost:18080
    depends_on:
      - openldap
    ports:
      - 18080:80
    networks:
      - openldap
      
networks:
  openldap:
    name: openldap
    
volumes:
  openldap-data:
```

on the other hand, if I use this docker-compose I get error like "Fatal: Couldn't create a secure connection to ldap://openldap-bitnami:1389 and LDAP_REQUIRE_STARTTLS is TRUE." 
```
version: "3.7"

services:
  openldap-bitnami:
    image: bitnami/openldap:2.6
    container_name: openldap-bitnami
    #volumes:
      #- openldap-data:/bitnami/openldap
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
    ports:
      - 1389:1389
      - 1636:1636
    networks:
      - openldap-bitnami
      
  openldap-bitnami-ui:
    image: wheelybird/ldap-user-manager:v1.7
    container_name: openldap-bitnami-ui
    environment:
      - LDAP_URI=ldap://openldap-bitnami:1389
      - LDAP_BASE_DN=dc=example,dc=org
      - LDAP_REQUIRE_STARTTLS=TRUE
      - LDAP_ADMINS_GROUP=admins
      - LDAP_ADMIN_BIND_DN=cn=admin,dc=example,dc=org
      - LDAP_ADMIN_BIND_PWD=adminpassword
      - LDAP_IGNORE_CERT_ERRORS=true
      - NO_HTTPS=TRUE
      - PASSWORD_HASH=SSHA
      - LDAP_VERBOSE_CONNECTION_LOGS=TRUE
      - SERVER_HOSTNAME=localhost:18081
    depends_on:
      - openldap-bitnami
    ports:
      - 18081:80
    networks:
      - openldap-bitnami      

networks:
  openldap-bitnami:
    name: openldap-bitnami
```

any idea why

**Comment by wheelybird** [comment]
You'd need to enable more verbose logging (https://github.com/wheelybird/ldap-user-manager#debugging-settings) to see what's happening.   That should hopefully give you enough information to fix the issue.
By the way, the latest version is `wheelybird/ldap-user-manager:v1.8` - that release fixed some bugs, so using that might help fix your issue.

**Comment by sergio11** [comment]
I am using this configuration and it works successfully after passing the setup at **"https://localhost:18080/setup"**


```
version: "3.8"


services:
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    volumes:
      - openldap-data:/var/lib/ldap
      - openldap-data:/etc/ldap/slapd.d
    environment:
      - LDAP_ORGANISATION=trustcertificationsystem
      - LDAP_DOMAIN=trustcertificationsystem.org
      - LDAP_ADMIN_PASSWORD=change_me
      - LDAP_RFC2307BIS_SCHEMA=true
      - LDAP_REMOVE_CONFIG_AFTER_SETUP=true
      - LDAP_TLS_VERIFY_CLIENT=never
    ports:
      - 389:389
      - 636:636
    networks:
      - openldap

  openldap-ui:
    image: wheelybird/ldap-user-manager:latest
    container_name: openldap-ui
    environment:
      - SERVER_HOSTNAME=localhost
      - LDAP_URI=ldap://openldap
      - LDAP_BASE_DN=dc=trustcertificationsystem,dc=org
      - LDAP_ADMINS_GROUP=admins
      - LDAP_ADMIN_BIND_DN=cn=admin,dc=trustcertificationsystem,dc=org
      - LDAP_ADMIN_BIND_PWD=change_me
      - LDAP_IGNORE_CERT_ERRORS=true
      - NO_HTTPS=TRUE
    depends_on:
      - openldap
    ports:
      - 18080:80
    networks:
      - openldap
      
networks:
  openldap:
    name: openldap
    
volumes:
  openldap-data:
    driver: local
```
