### ISSUE TITLE
Can't go past setup

### ISSUE THREAD

**Issue by foux** [wheelybird/ldap-user-manager#179]
**Version**
Version 1.8

**Describe the bug**
WHen going to `https://my.fq.dn/setup`, after authenticating, I get the following error : 

![image](https://user-images.githubusercontent.com/246550/195991059-cc9e4c4c-d82f-4246-a7ab-0c17323a7112.png)

This is on a brand new LDAP server, with the following compose : 
```
services:
  openldap:
    image: osixia/openldap:1.5.0
    restart: unless-stopped
    ports:
      - 636:636
    hostname: my.fq.dn
    volumes:
      - ./ldap/conf:/etc/ldap/slapd.d
      - ./ldap/datas:/var/lib/ldap
      - ./ssl/tfdn.app:/container/service/slapd/assets/certs
    environment:
      - LDAP_ORGANISATION=FQ.DN
      - LDAP_DOMAIN=fq.dn
      - LDAP_TLS_CRT_FILENAME=cert.pem
      - LDAP_TLS_KEY_FILENAME=key.pem
      - LDAP_TLS_CA_CRT_FILENAME=cert.pem
      - LDAP_RFC2307BIS_SCHEMA=true
    networks:
      - ldap
  ldap-user-manager:
    image: wheelybird/ldap-user-manager:v1.8
    restart: unless-stopped
    environment:
      - SERVER_HOSTNAME=my.fq.dn
      - LDAP_URI=ldap://openldap
      - LDAP_DEBUG=true
      - LDAP_VERBOSE_CONNECTION_LOGS=true
      - LDAP_BASE_DN=dc=fq,dc=dn"
      - LDAP_ADMINS_GROUP=admins
      - LDAP_ADMIN_BIND_DN=cn=admin,dc=fq,dc=dn
      - LDAP_ADMIN_BIND_PWD=admin
      - NO_HTTPS=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.ldap.rule=Host(`my.fq.dn`)
    networks:
      - ldap
      - web
networks:
  ldap:
  web:
    name: web
    external: true

```

I don't seem to see anything relevant in the logs.
Any idea where this might come from?

Thanks
