### ISSUE TITLE
cn with space or attribute with full name

### ISSUE THREAD

**Issue by DunklerPhoenix** [wheelybird/ldap-user-manager#199]
Heho
The cn value of a user holds its full name, but without space.

It would be great to change this to a readable form.

Now: JohnDoe
Would be good: John Doe

Or (I don't know if the first option breaks something) add a new attribute to the user that contains the full name e.g."John Doe"

An example for this problem is NextCloud. If I use cn the full name gets entered without space or I can use givenName and add the sn in (). Then it looks like John (Doe)

**Comment by DunklerPhoenix** [comment]
```
  accountmanager:
    image: wheelybird/ldap-user-manager:v1.10
    hostname: accountmanager
    environment:
      SERVER_HOSTNAME: "domain.com"
      LDAP_URI: "ldap://ldap"
      LDAP_BASE_DN: "dc=domain,dc=com"
      LDAP_REQUIRE_STARTTLS: "false"
      LDAP_ADMINS_GROUP: "admins"
      LDAP_ADMIN_BIND_DN: "cn=admin,dc=domain,dc=com"
      LDAP_ADMIN_BIND_PWD: "pw"
      LDAP_IGNORE_CERT_ERRORS: "true"
      ORGANISATION_NAME: "Domain"
      EMAIL_DOMAIN: "domain.com"
      SMTP_HOSTNAME: "postfix"
      SMTP_PORT: "25"
      EMAIL_FROM_ADDRESS: "mail@domain.com"
      EMAIL_FROM_NAME: "Centrallogin"
      ACCOUNT_REQUESTS_ENABLED: "false"
      SHOW_POSIX_ATTRIBUTES: "true"
      NO_HTTPS: "true"
      ENFORCE_SAFE_SYSTEM_NAMES: "true"
      USERNAME_FORMAT: "{first_name}.{last_name}"
    labels:
      traefik.enable: "true"
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
    depends_on:
      - ldap
    ports:
      - 38080:80
```

![8sl7JByKHK](https://user-images.githubusercontent.com/1261305/235693045-0b0e2243-d17a-4963-8a4f-2e5acd153600.png)
