### ISSUE TITLE
Can't get TLS to work

### ISSUE THREAD

**Issue by Oujiii** [wheelybird/ldap-user-manager#30]
Hi!

I'm new to LDAP and I'm trying to run with TLS (as I've heard is better for security), but I keep getting:
`Fatal: Couldn't create a secure connection to ldap://ldap.example.org and LDAP_REQUIRE_STARTTLS is TRUE.`

Also, if I put this behind a reverse proxy, the certificate I get with LE should be put where so the web panel can be secured by SSL?

Here is my docker-compose.yml
````
version: '3.3'
services:
    openldap:
        container_name: openldap
        environment:
            - LDAP_TLS=true
            - LDAP_ORGANISATION=example
            - LDAP_DOMAIN=example.org
            - LDAP_ADMIN_PASSWORD=secret
            - LDAP_CONFIG_PASSWORD=secret
            - LDAP_USES_NIS_SCHEMA=true
        ports:
            - '389:389'
            - '636:636'
        volumes:
            - '/opt/docker/openldap/var_lib_ldap:/var/lib/ldap'
            - '/opt/docker/openldap/etc_ldap_slapd.d:/etc/ldap/slapd.d'
        image: 'osixia/openldap:latest'
    ldap-user-manager:
        container_name: lum
        ports:
            - '80:80'
            - '443:443'
        environment:
            - SERVER_HOSTNAME=example.org
            - LDAP_URI=ldap://172.19.0.3
            - LDAP_BASE_DN=dc=example,dc=org
            - LDAP_REQUIRE_STARTTLS=TRUE
            - LDAP_ADMINS_GROUP=admins
            - LDAP_ADMIN_BIND_DN=cn=admin,dc=example,dc=org
            - LDAP_ADMIN_BIND_PWD=secret
            - LDAP_USES_NIS_SCHEMA=true
            - EMAIL_DOMAIN=example.org
        image: 'wheelybird/ldap-user-manager:latest'
````

Thank you
