### ISSUE TITLE
non www-root nginx proxied fails

### ISSUE THREAD

**Issue by fthiebolt** [wheelybird/ldap-user-manager#81]
Dear, I've been struggling a bit having ldap-user-manager running behind a nginx proxy: especially, i plan to serve it through https://<some site>/ldapadmin

To achieve this, i created a docker-compose yml
```
  ............
  web:
    image: wheelybird/ldap-user-manager
    restart: unless-stopped
    # container_name implies only one instance
    container_name: ldap-web
    volumes:
      - /etc/localtime:/etc/localtime:ro
    network_mode: bridge
    # Port mapping between the localhost and the container
    ports:
      - 8081:80
    environment:
      - TZ=Europe/Paris
      - SERVER_HOSTNAME=localhost
      - ORGANISATION_NAME=my-organisation
      - LDAP_URI=ldap://172.17.0.1
      - LDAP_BASE_DN=dc=my-domain,dc=my-organisation
      - LDAP_ADMINS_GROUP=admins
      - LDAP_ADMIN_BIND_DN=cn=admin,dc=my-domain,dc=my-organisation
      - LDAP_ADMIN_BIND_PWD="some password"
      - LDAP_IGNORE_CERT_ERRORS=true
```
I also declared a nginx section related to the /ldapadmin:
```
    # ############
    # PhpLDAPadmin
    location ^~ /ldapadmin {

        if ( $https = "" ) { rewrite ^ https://$http_host$request_uri? break; }

        access_log /var/log/nginx/phpldapadmin/access.log;
        error_log /var/log/nginx/phpldapadmin/error.log;

        proxy_pass http://127.0.0.1:8081/;  # warning '/' at the end set relative path from current location
    }
```

Of course, there are others things located at '/' of our site.
And just for you to know, this nginx setup perfectly works with phpLdapAdmin.
I have the feeling that there's a a kind of LAM_SERVER_PATH that is missing somewhere ...
Best
