### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by rpelissi** [wheelybird/ldap-user-manager#82]
**Check the debugging logs**
Please run the user manager with the debugging settings enabled.  This might help you resolve the issue without needing to create a bug report.   
Set `LDAP_DEBUG` and `LDAP_VERBOSE_CONNECTION_LOGS` to `TRUE` for LDAP issues.   

**Version**
Latest on dockerhub.

**Describe the bug**
I use rancher/dockerhub deployment and after setting all the necessary variables, I can access the web page but when I log in I got this:

Warning: ldap_get_entries() expects parameter 2 to be resource, boolean given in /opt/ldap_user_manager/includes/ldap_functions.inc.php on line 520

Warning: preg_grep() expects parameter 2 to be array, null given in /opt/ldap_user_manager/includes/ldap_functions.inc.php on line 526

Warning: Cannot modify header information - headers already sent by (output started at /opt/ldap_user_manager/includes/ldap_functions.inc.php:520) in /opt/ldap_user_manager/includes/web_functions.inc.php on line 69

Warning: Cannot modify header information - headers already sent by (output started at /opt/ldap_user_manager/includes/ldap_functions.inc.php:520) in /opt/ldap_user_manager/includes/web_functions.inc.php on line 70

Warning: Cannot modify header information - headers already sent by (output started at /opt/ldap_user_manager/includes/ldap_functions.inc.php:520) in /opt/ldap_user_manager/log_in/index.php on line 37.

**Comment by wheelybird** [comment]
Have you set LDAP_DEBUG to TRUE?  What do the logs say?

**Comment by mqu** [comment]
same error for me :
- tryied to login with admin, cn=admin,dc=ldapusermanager,dc=org, password 'admin',
- here is error log on login page :

```
Warning: ldap_get_entries() expects parameter 2 to be resource, boolean given in /opt/ldap_user_manager/includes/ldap_functions.inc.php on line 520
Warning: preg_grep() expects parameter 2 to be array, null given in /opt/ldap_user_manager/includes/ldap_functions.inc.php on line 526
Warning: Cannot modify header information - headers already sent by (output started at /opt/ldap_user_manager/includes/ldap_functions.inc.php:520) in /opt/ldap_user_manager/log_in/index.php on line 41
```
- this is my docker-compose file:

```
services:

  openldap:
    image: osixia/openldap:latest
    restart: unless-stopped
    ports:
      - 389:389
    environment:
      NODE_ENV: production
      LDAP_ORGANISATION: ldapusermanager
      LDAP_DOMAIN: ldapusermanager.org
      LDAP_ADMIN_PASSWORD: admin
      LDAP_RFC2307BIS_SCHEMA: 'true'
      LDAP_REMOVE_CONFIG_AFTER_SETUP: 'true'
      LDAP_TLS_VERIFY_CLIENT: never
      LDAP_DEBUG: 'true'
    volumes:
      - ./data/openldap/var_lib_ldap:/var/lib/ldap
      - ./data/openldap/etc_ldap_slapd.d:/etc/ldap/slapd.d

  # src : https://github.com/wheelybird/ldap-user-manager
  app:
    image: wheelybird/ldap-user-manager:latest
    restart: unless-stopped
    ports:
      - 8080:80
      - 4443:443
    environment:
      SERVER_HOSTNAME: localhost
      LDAP_DEBUG: 'true'
      LDAP_URI: ldap://openldap
      LDAP_BASE_DN: dc=ldapusermanager,dc=org
      LDAP_ADMINS_GROUP: admins
      LDAP_ADMIN_BIND_DN: cn=admin,dc=ldapusermanager,dc=org
      LDAP_ADMIN_BIND_PWD: admin
      LDAP_IGNORE_CERT_ERRORS: 'true'
      NO_HTTPS: 'true'
```
- ldap database is empty before starting application
- here is log from docker-compose: https://gist.github.com/mqu/6b99911cf401be39ee2323413f0f5295
- I tryied to follow instruction from [testing with LDAP container](https://github.com/wheelybird/ldap-user-manager#testing-with-an-openldap-container).
- I am going to extend Debug logs.

best regards, Marc.
